name: Publish Articles

on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
      - 'src/**'
      - '**.py'
      - '**.md'
      - '**.c'
      - '**.ltx'
      - 'publ.yml'

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install TeXLive
        run: |
          sudo apt-get update
          sudo apt install -y texlive-luatex texlive-latex-base

      - name: Install C Compiler and Library
        run: cc -v

      - name: Make Post
        run: python3 make.py post

      - name: Make Batch
        run: |
          mkdir ./public/batch >/dev/null 2>&1
          python3 make.py batch

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main --rebase
          git add .
          git commit -m "chore: automated publish" || echo "no changes to commit"
          git push origin HEAD:main